arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005 
  position_only_ik: true  # Gripper will only change position, not orientation
  
#this file to  decleare and configure the kinematic solver in the moveit plugin that we will use